# Generated by Django 4.0.4 on 2022-05-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(help_text="Iltimos to'g\ri URL kiriting!"),
        ),
    ]
